<?php

namespace ContainerS6mGDBa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yq4ygE1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yq4ygE1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yq4ygE1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'offre2' => ['privates', '.errored..service_locator.yq4ygE1.App\\Entity\\Offre2', NULL, 'Cannot autowire service ".service_locator.yq4ygE1": it references class "App\\Entity\\Offre2" but no such service exists.'],
        ], [
            'offre2' => 'App\\Entity\\Offre2',
        ]);
    }
}
