<?php

namespace ContainerS6mGDBa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PTnBlSkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PTnBlSk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PTnBlSk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'reservationCovoiturage' => ['privates', '.errored..service_locator.PTnBlSk.App\\Entity\\ReservationCovoiturage', NULL, 'Cannot autowire service ".service_locator.PTnBlSk": it references class "App\\Entity\\ReservationCovoiturage" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'reservationCovoiturage' => 'App\\Entity\\ReservationCovoiturage',
        ]);
    }
}
