<?php

namespace ContainerS6mGDBa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IUDUMQzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iUDUMQz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iUDUMQz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'reservationBu' => ['privates', '.errored..service_locator.iUDUMQz.App\\Entity\\ReservationBus', NULL, 'Cannot autowire service ".service_locator.iUDUMQz": it references class "App\\Entity\\ReservationBus" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'reservationBu' => 'App\\Entity\\ReservationBus',
        ]);
    }
}
