<?php

namespace ContainerS6mGDBa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JKD5lbQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JKD5lbQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JKD5lbQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'reservation_busRepository' => ['privates', 'App\\Repository\\ReservationBusRepository', 'getReservationBusRepositoryService', true],
        ], [
            'entityManager' => '?',
            'reservation_busRepository' => 'App\\Repository\\ReservationBusRepository',
        ]);
    }
}
