<?php

namespace ContainerS6mGDBa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AJOPCwAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AJOPCwA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AJOPCwA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservation_covoiturageRepository' => ['privates', 'App\\Repository\\ReservationCovoiturageRepository', 'getReservationCovoiturageRepositoryService', true],
        ], [
            'reservation_covoiturageRepository' => 'App\\Repository\\ReservationCovoiturageRepository',
        ]);
    }
}
