<?php

namespace ContainerS6mGDBa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OMx7lkoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OMx7lko' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OMx7lko'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'qrcodeService' => ['privates', 'App\\Services\\QrcodeService', 'getQrcodeServiceService', true],
            'reservationBu' => ['privates', '.errored..service_locator.OMx7lko.App\\Entity\\ReservationBus', NULL, 'Cannot autowire service ".service_locator.OMx7lko": it references class "App\\Entity\\ReservationBus" but no such service exists.'],
        ], [
            'qrcodeService' => 'App\\Services\\QrcodeService',
            'reservationBu' => 'App\\Entity\\ReservationBus',
        ]);
    }
}
