<?php

namespace ContainerS6mGDBa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffre3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pyOx2fm.App\Entity\Offre' shared service.
     *
     * @return \App\Entity\Offre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.pyOx2fm": it references class "App\\Entity\\Offre" but no such service exists.');
    }
}
