<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'idUser', '' . "\0" . 'App\\Entity\\User' . "\0" . 'nomU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'prenomU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'emailU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'telU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'roleU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'passwordU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userName', '' . "\0" . 'App\\Entity\\User' . "\0" . 'matriculeU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'pfpU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'identifiant', '' . "\0" . 'App\\Entity\\User' . "\0" . 'active'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'idUser', '' . "\0" . 'App\\Entity\\User' . "\0" . 'nomU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'prenomU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'emailU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'telU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'roleU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'passwordU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userName', '' . "\0" . 'App\\Entity\\User' . "\0" . 'matriculeU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'pfpU', '' . "\0" . 'App\\Entity\\User' . "\0" . 'identifiant', '' . "\0" . 'App\\Entity\\User' . "\0" . 'active'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdUser(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdUser();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser', []);

        return parent::getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomU(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomU', []);

        return parent::getNomU();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomU(string $nomU): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomU', [$nomU]);

        return parent::setNomU($nomU);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomU(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomU', []);

        return parent::getPrenomU();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomU(string $prenomU): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomU', [$prenomU]);

        return parent::setPrenomU($prenomU);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailU(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailU', []);

        return parent::getEmailU();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailU(string $emailU): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailU', [$emailU]);

        return parent::setEmailU($emailU);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelU(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelU', []);

        return parent::getTelU();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelU(string $telU): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelU', [$telU]);

        return parent::setTelU($telU);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoleU(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoleU', []);

        return parent::getRoleU();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoleU(string $roleU): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoleU', [$roleU]);

        return parent::setRoleU($roleU);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordU(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordU', []);

        return parent::getPasswordU();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordU(string $passwordU): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordU', [$passwordU]);

        return parent::setPasswordU($passwordU);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserName', []);

        return parent::getUserName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserName(string $userName): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserName', [$userName]);

        return parent::setUserName($userName);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatriculeU(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatriculeU', []);

        return parent::getMatriculeU();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatriculeU(string $matriculeU): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatriculeU', [$matriculeU]);

        return parent::setMatriculeU($matriculeU);
    }

    /**
     * {@inheritDoc}
     */
    public function getPfpU()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPfpU', []);

        return parent::getPfpU();
    }

    /**
     * {@inheritDoc}
     */
    public function setPfpU($pfpU): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPfpU', [$pfpU]);

        return parent::setPfpU($pfpU);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifiant(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentifiant', []);

        return parent::getIdentifiant();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentifiant(?string $identifiant): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentifiant', [$identifiant]);

        return parent::setIdentifiant($identifiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(?int $active): \App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
