<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Offre extends \App\Entity\Offre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'idOffre', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'imageVehicule', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'prenomChauff', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'numChauff', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'dateOffre', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'heure', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'prixOffre', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'depart', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'destination', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'placesDispo', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'idUser'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'idOffre', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'imageVehicule', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'prenomChauff', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'numChauff', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'dateOffre', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'heure', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'prixOffre', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'depart', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'destination', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'placesDispo', '' . "\0" . 'App\\Entity\\Offre' . "\0" . 'idUser'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Offre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdOffre(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdOffre();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOffre', []);

        return parent::getIdOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageVehicule(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageVehicule', []);

        return parent::getImageVehicule();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageVehicule(string $imageVehicule): \App\Entity\Offre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageVehicule', [$imageVehicule]);

        return parent::setImageVehicule($imageVehicule);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomChauff(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomChauff', []);

        return parent::getPrenomChauff();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomChauff(string $prenomChauff): \App\Entity\Offre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomChauff', [$prenomChauff]);

        return parent::setPrenomChauff($prenomChauff);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumChauff(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumChauff', []);

        return parent::getNumChauff();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumChauff(string $numChauff): \App\Entity\Offre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumChauff', [$numChauff]);

        return parent::setNumChauff($numChauff);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOffre(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOffre', []);

        return parent::getDateOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOffre(\DateTimeInterface $dateOffre): \App\Entity\Offre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOffre', [$dateOffre]);

        return parent::setDateOffre($dateOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeure(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeure', []);

        return parent::getHeure();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeure(\DateTimeInterface $heure): \App\Entity\Offre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeure', [$heure]);

        return parent::setHeure($heure);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixOffre(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixOffre', []);

        return parent::getPrixOffre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixOffre(int $prixOffre): \App\Entity\Offre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixOffre', [$prixOffre]);

        return parent::setPrixOffre($prixOffre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepart(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepart', []);

        return parent::getDepart();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepart(string $depart): \App\Entity\Offre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepart', [$depart]);

        return parent::setDepart($depart);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestination(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestination', []);

        return parent::getDestination();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestination(string $destination): \App\Entity\Offre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestination', [$destination]);

        return parent::setDestination($destination);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlacesDispo(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlacesDispo', []);

        return parent::getPlacesDispo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlacesDispo(int $placesDispo): \App\Entity\Offre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlacesDispo', [$placesDispo]);

        return parent::setPlacesDispo($placesDispo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser', []);

        return parent::getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUser(?\App\Entity\User $idUser): \App\Entity\Offre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUser', [$idUser]);

        return parent::setIdUser($idUser);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
