<?php

namespace ContainerW45QeCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J6rIwD_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j6rIwD.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j6rIwD.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservationCovoiturage' => ['privates', '.errored..service_locator.j6rIwD..App\\Entity\\ReservationCovoiturage', NULL, 'Cannot autowire service ".service_locator.j6rIwD.": it references class "App\\Entity\\ReservationCovoiturage" but no such service exists.'],
        ], [
            'reservationCovoiturage' => 'App\\Entity\\ReservationCovoiturage',
        ]);
    }
}
