<?php

namespace ContainerW45QeCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PGVXQWIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pGVXQWI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pGVXQWI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservationBu' => ['privates', '.errored..service_locator.pGVXQWI.App\\Entity\\ReservationBus', NULL, 'Cannot autowire service ".service_locator.pGVXQWI": it references class "App\\Entity\\ReservationBus" but no such service exists.'],
        ], [
            'reservationBu' => 'App\\Entity\\ReservationBus',
        ]);
    }
}
