<?php

namespace ContainerW45QeCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W9gzBhPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W9gzBhP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W9gzBhP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservation_busRepository' => ['privates', 'App\\Repository\\ReservationBusRepository', 'getReservationBusRepositoryService', true],
        ], [
            'reservation_busRepository' => 'App\\Repository\\ReservationBusRepository',
        ]);
    }
}
