<?php

namespace ContainerW45QeCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationCovoiturage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.j6rIwD..App\Entity\ReservationCovoiturage' shared service.
     *
     * @return \App\Entity\ReservationCovoiturage
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.j6rIwD.": it references class "App\\Entity\\ReservationCovoiturage" but no such service exists.');
    }
}
