<?php

namespace ContainerW45QeCb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationBusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OMx7lko.App\Entity\ReservationBus' shared service.
     *
     * @return \App\Entity\ReservationBus
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.OMx7lko": it references class "App\\Entity\\ReservationBus" but no such service exists.');
    }
}
