<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW45QeCb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW45QeCb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW45QeCb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW45QeCb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW45QeCb\App_KernelDevDebugContainer([
    'container.build_hash' => 'W45QeCb',
    'container.build_id' => 'ead36a84',
    'container.build_time' => 1682601175,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW45QeCb');
